import pyttsx3
print("==========================ATM=====================")
fri = pyttsx3.init()
name=input("Enter your  name :")
pin=input("Enter you pin :")

print("loading...")
print("loading...")
print("loading...")
print("loading...")
print(name +" which transaction do you want to perform\n1 - Withdaraw\n2 - Deposit\n3 -check balance")
ans=input(" :")

if ans=="1":
    o=input("Enter amount for withdrawals :")
    print("processing...")
    print("processing...")
    print("processing...")
    print("processing...")
    print("processing...")
    print("processing...")
    print("Please take your cash  $$$")
    print("Thank you for banking with us")
    fri.say("Thank you for banking with us")
if ans=="2":
    t=input("Enter amount for deposit :")
    print("processing...")
    print("processing...")
    print("processing...")
    print("processing...")
    print("processing...")
    print("processing...")
    print("Your cash have deposited into the bank $$$")
    print("Thank you for banking with us")
    fri.say("Thank you for banking with us")
if ans=="3":
    print("Your main balance is -500$")
    fri.say("Your main balance is -500$")
    print("Please pay back your dept")
    fri.say("Please pay back your dept")
    print("Broke ass nigger")
    fri.say("Broke ass nigger")
    print("Thank you for banking with us")
    fri.say("Thank you for banking with us")

fri.runAndWait()